import React, { useEffect, useState } from 'react';
import Background from '../effects/Background';
import GlassCard from '../ui/GlassCard';
import { 
  AlertTriangle, CheckCircle, XCircle, FileWarning, 
  Briefcase, Truck, Users, Activity 
} from 'lucide-react';

const ReportPage = () => {
  const [report, setReport] = useState(null);

  useEffect(() => {
    const storedData = localStorage.getItem('auditReportData');
    if (storedData) {
      setReport(JSON.parse(storedData));
    }
  }, []);

  if (!report) return <div className="text-white text-center mt-20">Loading Report...</div>;

  // --- 1. DATA TRANSFORMATION HELPERS ---
  // Convert Backend Status to UI Colors
  const getStatusColor = (status) => {
    const s = (status || "").toLowerCase();
    if (s.includes('compliant') || s.includes('positive') || s.includes('low')) return "text-emerald-400 bg-emerald-500/10 border-emerald-500/20";
    if (s.includes('risk') || s.includes('non') || s.includes('high')) return "text-red-400 bg-red-500/10 border-red-500/20";
    return "text-yellow-400 bg-yellow-500/10 border-yellow-500/20";
  };

  const getIcon = (status) => {
    const s = (status || "").toLowerCase();
    if (s.includes('compliant') || s.includes('positive')) return <CheckCircle className="w-5 h-5" />;
    if (s.includes('risk') || s.includes('non')) return <XCircle className="w-5 h-5" />;
    return <AlertTriangle className="w-5 h-5" />;
  };

  // Map Pydantic Nested Data to Flat Array for UI Loop
  const complianceItems = [
    { name: "Minimum Wage", ...report.labor_code_analysis?.wages?.minimum_wage_status },
    { name: "Equal Pay", ...report.labor_code_analysis?.wages?.equal_pay_status },
    { name: "Safety Systems", ...report.labor_code_analysis?.osh?.safety_systems_status },
    { name: "Accidents", ...report.labor_code_analysis?.osh?.accident_records_status },
    { name: "Unionization", ...report.labor_code_analysis?.ir?.unionization_status },
    { name: "Disputes", ...report.labor_code_analysis?.ir?.disputes_strikes_status }
  ];

  // Safely extract Workforce numbers
  const permEmployees = report.workforce_profile?.find(w => w.category.includes('Permanent Employee'))?.total_count || "N/A";
  const contractWorkers = report.workforce_profile?.find(w => w.category.includes('Contract') || w.category.includes('Worker'))?.total_count || "N/A";

  return (
    <div className="min-h-screen relative font-sans text-slate-100 selection:bg-blue-500/30">
      <Background />
      
      <main className="container mx-auto px-4 py-10 max-w-6xl">
        {/* Report Header */}
        <div className="mb-10 flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-cyan-400 mb-2">
              Audit Report: {report.company_name}
            </h1>
            <p className="text-slate-400">Generated by AutoLabor Compliance Agent • {report.report_period}</p>
          </div>
          <div className="px-4 py-2 bg-blue-500/10 border border-blue-500/20 rounded-full text-blue-300 text-sm">
            Status: Audit Complete
          </div>
        </div>

        {/* Dashboard Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-slide-up pb-20">
          
          {/* Risk Score */}
          <GlassCard className={`md:col-span-1 border-l-4 ${report.overall_risk_score?.includes('High') ? 'border-l-red-500' : 'border-l-yellow-500'} bg-slate-800/40`}>
            <h3 className="text-slate-400 text-xs uppercase tracking-wider font-semibold mb-2">Overall Risk</h3>
            <div className="flex items-baseline gap-3 mt-1">
              <span className="text-5xl font-bold text-white">{report.overall_risk_score}</span>
              <Activity className="text-slate-500 w-8 h-8 opacity-50" />
            </div>
            <p className="text-xs text-slate-500 mt-4">Based on forensic analysis of Annual Reports & BRSR.</p>
          </GlassCard>

          {/* NEW: Labour Code Impact (Forensic) */}
          <GlassCard className="md:col-span-2 bg-gradient-to-r from-red-900/20 to-slate-900/40 border-red-500/30">
            <h3 className="text-red-400 text-xs uppercase tracking-wider font-semibold mb-4 flex items-center gap-2">
               <FileWarning className="w-4 h-4" /> Labour Code Financial Impact
            </h3>
            <div className="flex items-end justify-between">
                <div>
                    <div className="text-4xl font-bold text-white font-mono">
                        {report.Labour_Provision || report.labour_code_impact?.provision_amount || "N/A"}
                    </div>
                    <p className="text-sm text-slate-400 mt-2 max-w-lg">
                        {report.Labour_Provision_Desc || report.labour_code_impact?.impact_description || "No provision note detected."}
                    </p>
                </div>
                <div className="text-right">
                    <div className="text-xs text-slate-500 uppercase font-bold">Status</div>
                    <div className="text-red-300 bg-red-900/40 px-3 py-1 rounded text-sm mt-1">Provision Identified</div>
                </div>
            </div>
          </GlassCard>

          {/* Financials */}
          <GlassCard className="md:col-span-1 bg-slate-800/40">
            <h3 className="text-slate-400 text-xs uppercase tracking-wider font-semibold mb-6">Financial Intelligence</h3>
            <div className="space-y-4">
              <div className="flex justify-between border-b border-white/5 pb-2">
                  <span className="text-slate-400">Revenue</span>
                  <span className="text-white font-mono">{report.api_financials?.revenue}</span>
              </div>
              <div className="flex justify-between border-b border-white/5 pb-2">
                  <span className="text-slate-400">Net Income</span>
                  <span className="text-white font-mono">{report.api_financials?.net_income}</span>
              </div>
              <div className="flex justify-between border-b border-white/5 pb-2">
                  <span className="text-slate-400">Emp. Cost</span>
                  <span className="text-white font-mono">{report.api_financials?.employee_cost}</span>
              </div>
            </div>
          </GlassCard>

          {/* Compliance Checklist (Mapped from Backend Object) */}
          <GlassCard className="md:col-span-2 bg-slate-800/40">
            <h3 className="text-slate-400 text-xs uppercase tracking-wider font-semibold mb-6">Regulatory Compliance</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {complianceItems.map((item, idx) => {
                const colorClass = getStatusColor(item.status);
                return (
                    <div key={idx} className={`flex items-center justify-between p-3 rounded-lg border ${colorClass} bg-opacity-10 transition-colors`}>
                    <div className="flex items-center gap-3">
                        {getIcon(item.status)}
                        <span className="font-medium text-slate-200 text-sm">{item.name}</span>
                    </div>
                    <span className="text-xs font-bold uppercase tracking-wider opacity-80">
                        {item.status || "N/A"}
                    </span>
                    </div>
                );
              })}
            </div>
          </GlassCard>

          {/* Business Intel (New) */}
          <GlassCard className="md:col-span-2 bg-slate-800/40">
             <div className="grid grid-cols-2 gap-8">
                <div>
                    <h3 className="text-slate-400 text-xs uppercase tracking-wider font-semibold mb-4 flex gap-2">
                        <Briefcase className="w-4 h-4" /> Key Products
                    </h3>
                    <p className="text-sm text-slate-300 leading-relaxed">
                        {report.Top_Products || "Data not extracted."}
                    </p>
                </div>
                <div>
                    <h3 className="text-slate-400 text-xs uppercase tracking-wider font-semibold mb-4 flex gap-2">
                        <Truck className="w-4 h-4" /> Supply Chain
                    </h3>
                    <p className="text-sm text-slate-300 leading-relaxed">
                        {report.Top_Vendors || "Data not extracted."}
                    </p>
                </div>
             </div>
          </GlassCard>

          {/* Workforce Stats */}
          <GlassCard className="md:col-span-1 bg-slate-800/40">
            <h3 className="text-slate-400 text-xs uppercase tracking-wider font-semibold mb-6">Workforce</h3>
            <div className="space-y-4">
              <div className="p-4 rounded-lg bg-white/5 border border-white/5">
                <div className="text-3xl font-bold text-white mb-1 font-mono">{permEmployees}</div>
                <div className="text-xs text-slate-400 flex items-center gap-2"><Users className="w-3 h-3"/> Permanent Employees</div>
              </div>
              <div className="p-4 rounded-lg bg-white/5 border border-white/5">
                <div className="text-3xl font-bold text-white mb-1 font-mono">{contractWorkers}</div>
                <div className="text-xs text-slate-400 flex items-center gap-2"><Users className="w-3 h-3"/> Contract / Other</div>
              </div>
            </div>
          </GlassCard>

        </div>
      </main>
    </div>
  );
};

export default ReportPage;